name: match_a_man
description: A social sports and events mobile app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  geocoding: ^3.0.0
  geolocator: ^14.0.2
  google_fonts: ^6.2.1
  go_router: ^14.8.1
  image_cropper: ^8.0.2
  in_app_purchase: ^3.3.0
  image_picker: ^1.1.2
  supabase_flutter: ^2.9.1
  url_launcher: ^6.3.1
  firebase_core: ^4.10.0
  firebase_messaging: ^16.3.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.1.1
  share_plus: ^10.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/auth/apple_logo.png
    - assets/auth/google_logo.png
    - assets/branding/akanzi_logo.jpg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/branding/akanzi_logo.jpg"
  adaptive_icon_background: "#FDFBF9"
  adaptive_icon_foreground: "assets/branding/akanzi_logo.jpg"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/branding/akanzi_logo.jpg"
    background_color: "#FDFBF9"
    theme_color: "#FF7E79"
  windows:
    generate: true
    image_path: "assets/branding/akanzi_logo.jpg"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/branding/akanzi_logo.jpg"

flutter_native_splash:
  color: "#FDFBF9"
  image: assets/branding/akanzi_logo.jpg
  android: true
  ios: true
  web: true
  android_12:
    color: "#FDFBF9"
    image: assets/branding/akanzi_logo.jpg
    icon_background_color: "#FDFBF9"
